-- Team aliases seed — maps every common abbreviation / short form the venue
-- scrapers emit (DK, FD, ESPN) to the canonical full team name the matcher
-- uses. The matcher normalizes to lowercase-no-punctuation, so aliases and
-- canonicals are stored in that form.
--
-- Canonical = _normalize(Poly marketSides[].team.name). The scraper
-- canonicalizes its own team strings against this table, then compares as a
-- frozenset of canonicals. Exact-match is tried first; rapidfuzz >= 88
-- is the fallback threshold.
--
-- Idempotent — safe to re-run (unique (sport, alias) guards upserts).

-- ============================================================================
-- MLB (30)
-- ============================================================================
insert into team_aliases (sport, canonical, alias) values
  -- AL East
  ('MLB','baltimore orioles',  'bal orioles'),
  ('MLB','baltimore orioles',  'bal'),
  ('MLB','baltimore orioles',  'orioles'),
  ('MLB','boston red sox',     'bos red sox'),
  ('MLB','boston red sox',     'bos'),
  ('MLB','boston red sox',     'red sox'),
  ('MLB','new york yankees',   'ny yankees'),
  ('MLB','new york yankees',   'nyy'),
  ('MLB','new york yankees',   'yankees'),
  ('MLB','tampa bay rays',     'tb rays'),
  ('MLB','tampa bay rays',     'tb'),
  ('MLB','tampa bay rays',     'rays'),
  ('MLB','toronto blue jays',  'tor blue jays'),
  ('MLB','toronto blue jays',  'tor'),
  ('MLB','toronto blue jays',  'blue jays'),
  -- AL Central
  ('MLB','chicago white sox',  'chi white sox'),
  ('MLB','chicago white sox',  'chw'),
  ('MLB','chicago white sox',  'cws'),
  ('MLB','chicago white sox',  'white sox'),
  ('MLB','cleveland guardians','cle guardians'),
  ('MLB','cleveland guardians','cle'),
  ('MLB','cleveland guardians','guardians'),
  ('MLB','detroit tigers',     'det tigers'),
  ('MLB','detroit tigers',     'det'),
  ('MLB','detroit tigers',     'tigers'),
  ('MLB','kansas city royals', 'kc royals'),
  ('MLB','kansas city royals', 'kc'),
  ('MLB','kansas city royals', 'royals'),
  ('MLB','minnesota twins',    'min twins'),
  ('MLB','minnesota twins',    'min'),
  ('MLB','minnesota twins',    'twins'),
  -- AL West
  ('MLB','athletics',          'oakland athletics'),
  ('MLB','athletics',          'oak athletics'),
  ('MLB','athletics',          'oak'),
  ('MLB','athletics',          'ath'),
  ('MLB','athletics',          'as'),
  ('MLB','houston astros',     'hou astros'),
  ('MLB','houston astros',     'hou'),
  ('MLB','houston astros',     'astros'),
  ('MLB','los angeles angels', 'la angels'),
  ('MLB','los angeles angels', 'laa'),
  ('MLB','los angeles angels', 'angels'),
  ('MLB','seattle mariners',   'sea mariners'),
  ('MLB','seattle mariners',   'sea'),
  ('MLB','seattle mariners',   'mariners'),
  ('MLB','texas rangers',      'tex rangers'),
  ('MLB','texas rangers',      'tex'),
  ('MLB','texas rangers',      'rangers'),
  -- NL East
  ('MLB','atlanta braves',     'atl braves'),
  ('MLB','atlanta braves',     'atl'),
  ('MLB','atlanta braves',     'braves'),
  ('MLB','miami marlins',      'mia marlins'),
  ('MLB','miami marlins',      'mia'),
  ('MLB','miami marlins',      'marlins'),
  ('MLB','new york mets',      'ny mets'),
  ('MLB','new york mets',      'nym'),
  ('MLB','new york mets',      'mets'),
  ('MLB','philadelphia phillies','phi phillies'),
  ('MLB','philadelphia phillies','phi'),
  ('MLB','philadelphia phillies','phillies'),
  ('MLB','washington nationals','was nationals'),
  ('MLB','washington nationals','wsh nationals'),
  ('MLB','washington nationals','wsh'),
  ('MLB','washington nationals','was'),
  ('MLB','washington nationals','nationals'),
  -- NL Central
  ('MLB','chicago cubs',       'chi cubs'),
  ('MLB','chicago cubs',       'chc'),
  ('MLB','chicago cubs',       'cubs'),
  ('MLB','cincinnati reds',    'cin reds'),
  ('MLB','cincinnati reds',    'cin'),
  ('MLB','cincinnati reds',    'reds'),
  ('MLB','milwaukee brewers',  'mil brewers'),
  ('MLB','milwaukee brewers',  'mil'),
  ('MLB','milwaukee brewers',  'brewers'),
  ('MLB','pittsburgh pirates', 'pit pirates'),
  ('MLB','pittsburgh pirates', 'pit'),
  ('MLB','pittsburgh pirates', 'pirates'),
  ('MLB','st louis cardinals', 'stl cardinals'),
  ('MLB','st louis cardinals', 'stl'),
  ('MLB','st louis cardinals', 'cardinals'),
  -- NL West
  ('MLB','arizona diamondbacks','ari diamondbacks'),
  ('MLB','arizona diamondbacks','ari'),
  ('MLB','arizona diamondbacks','az'),
  ('MLB','arizona diamondbacks','diamondbacks'),
  ('MLB','arizona diamondbacks','dbacks'),
  ('MLB','colorado rockies',   'col rockies'),
  ('MLB','colorado rockies',   'col'),
  ('MLB','colorado rockies',   'rockies'),
  ('MLB','los angeles dodgers','la dodgers'),
  ('MLB','los angeles dodgers','lad'),
  ('MLB','los angeles dodgers','dodgers'),
  ('MLB','san diego padres',   'sd padres'),
  ('MLB','san diego padres',   'sd'),
  ('MLB','san diego padres',   'padres'),
  ('MLB','san francisco giants','sf giants'),
  ('MLB','san francisco giants','sf'),
  ('MLB','san francisco giants','giants'),
  -- Handle Polymarket's "St. Louis Cardinals" with period form
  ('MLB','st louis cardinals', 'st louis cardinals'),
  ('MLB','st louis cardinals', 'saint louis cardinals')
on conflict (sport, alias) do nothing;

-- ============================================================================
-- NBA (30)
-- ============================================================================
insert into team_aliases (sport, canonical, alias) values
  ('NBA','atlanta hawks',         'atl hawks'),
  ('NBA','atlanta hawks',         'atl'),
  ('NBA','atlanta hawks',         'hawks'),
  ('NBA','boston celtics',        'bos celtics'),
  ('NBA','boston celtics',        'bos'),
  ('NBA','boston celtics',        'celtics'),
  ('NBA','brooklyn nets',         'bkn nets'),
  ('NBA','brooklyn nets',         'brk nets'),
  ('NBA','brooklyn nets',         'bkn'),
  ('NBA','brooklyn nets',         'brk'),
  ('NBA','brooklyn nets',         'nets'),
  ('NBA','charlotte hornets',     'cha hornets'),
  ('NBA','charlotte hornets',     'cha'),
  ('NBA','charlotte hornets',     'cho'),
  ('NBA','charlotte hornets',     'hornets'),
  ('NBA','chicago bulls',         'chi bulls'),
  ('NBA','chicago bulls',         'chi'),
  ('NBA','chicago bulls',         'bulls'),
  ('NBA','cleveland cavaliers',   'cle cavaliers'),
  ('NBA','cleveland cavaliers',   'cle'),
  ('NBA','cleveland cavaliers',   'cavaliers'),
  ('NBA','cleveland cavaliers',   'cavs'),
  ('NBA','dallas mavericks',      'dal mavericks'),
  ('NBA','dallas mavericks',      'dal'),
  ('NBA','dallas mavericks',      'mavericks'),
  ('NBA','dallas mavericks',      'mavs'),
  ('NBA','denver nuggets',        'den nuggets'),
  ('NBA','denver nuggets',        'den'),
  ('NBA','denver nuggets',        'nuggets'),
  ('NBA','detroit pistons',       'det pistons'),
  ('NBA','detroit pistons',       'det'),
  ('NBA','detroit pistons',       'pistons'),
  ('NBA','golden state warriors', 'gs warriors'),
  ('NBA','golden state warriors', 'gsw'),
  ('NBA','golden state warriors', 'gs'),
  ('NBA','golden state warriors', 'warriors'),
  ('NBA','houston rockets',       'hou rockets'),
  ('NBA','houston rockets',       'hou'),
  ('NBA','houston rockets',       'rockets'),
  ('NBA','indiana pacers',        'ind pacers'),
  ('NBA','indiana pacers',        'ind'),
  ('NBA','indiana pacers',        'pacers'),
  ('NBA','la clippers',           'la clippers'),
  ('NBA','la clippers',           'lac'),
  ('NBA','la clippers',           'clippers'),
  ('NBA','la clippers',           'los angeles clippers'),
  ('NBA','los angeles lakers',    'la lakers'),
  ('NBA','los angeles lakers',    'lal'),
  ('NBA','los angeles lakers',    'lakers'),
  ('NBA','memphis grizzlies',     'mem grizzlies'),
  ('NBA','memphis grizzlies',     'mem'),
  ('NBA','memphis grizzlies',     'grizzlies'),
  ('NBA','miami heat',            'mia heat'),
  ('NBA','miami heat',            'mia'),
  ('NBA','miami heat',            'heat'),
  ('NBA','milwaukee bucks',       'mil bucks'),
  ('NBA','milwaukee bucks',       'mil'),
  ('NBA','milwaukee bucks',       'bucks'),
  ('NBA','minnesota timberwolves','min timberwolves'),
  ('NBA','minnesota timberwolves','min'),
  ('NBA','minnesota timberwolves','timberwolves'),
  ('NBA','minnesota timberwolves','wolves'),
  ('NBA','new orleans pelicans',  'no pelicans'),
  ('NBA','new orleans pelicans',  'nop'),
  ('NBA','new orleans pelicans',  'pelicans'),
  ('NBA','new york knicks',       'ny knicks'),
  ('NBA','new york knicks',       'nyk'),
  ('NBA','new york knicks',       'knicks'),
  ('NBA','oklahoma city thunder', 'okc thunder'),
  ('NBA','oklahoma city thunder', 'okc'),
  ('NBA','oklahoma city thunder', 'thunder'),
  ('NBA','orlando magic',         'orl magic'),
  ('NBA','orlando magic',         'orl'),
  ('NBA','orlando magic',         'magic'),
  ('NBA','philadelphia 76ers',    'phi 76ers'),
  ('NBA','philadelphia 76ers',    'phi'),
  ('NBA','philadelphia 76ers',    '76ers'),
  ('NBA','philadelphia 76ers',    'sixers'),
  ('NBA','phoenix suns',          'pho suns'),
  ('NBA','phoenix suns',          'phx suns'),
  ('NBA','phoenix suns',          'pho'),
  ('NBA','phoenix suns',          'phx'),
  ('NBA','phoenix suns',          'suns'),
  ('NBA','portland trail blazers','por trail blazers'),
  ('NBA','portland trail blazers','por'),
  ('NBA','portland trail blazers','trail blazers'),
  ('NBA','portland trail blazers','blazers'),
  ('NBA','sacramento kings',      'sac kings'),
  ('NBA','sacramento kings',      'sac'),
  ('NBA','sacramento kings',      'kings'),
  ('NBA','san antonio spurs',     'sa spurs'),
  ('NBA','san antonio spurs',     'sas'),
  ('NBA','san antonio spurs',     'spurs'),
  ('NBA','toronto raptors',       'tor raptors'),
  ('NBA','toronto raptors',       'tor'),
  ('NBA','toronto raptors',       'raptors'),
  ('NBA','utah jazz',             'uta jazz'),
  ('NBA','utah jazz',             'uta'),
  ('NBA','utah jazz',             'jazz'),
  ('NBA','washington wizards',    'was wizards'),
  ('NBA','washington wizards',    'wsh wizards'),
  ('NBA','washington wizards',    'was'),
  ('NBA','washington wizards',    'wsh'),
  ('NBA','washington wizards',    'wizards')
on conflict (sport, alias) do nothing;

-- ============================================================================
-- NHL (32)
-- ============================================================================
insert into team_aliases (sport, canonical, alias) values
  ('NHL','anaheim ducks',           'ana ducks'),
  ('NHL','anaheim ducks',           'ana'),
  ('NHL','anaheim ducks',           'ducks'),
  ('NHL','boston bruins',           'bos bruins'),
  ('NHL','boston bruins',           'bos'),
  ('NHL','boston bruins',           'bruins'),
  ('NHL','buffalo sabres',          'buf sabres'),
  ('NHL','buffalo sabres',          'buf'),
  ('NHL','buffalo sabres',          'sabres'),
  ('NHL','calgary flames',          'cgy flames'),
  ('NHL','calgary flames',          'cgy'),
  ('NHL','calgary flames',          'flames'),
  ('NHL','carolina hurricanes',     'car hurricanes'),
  ('NHL','carolina hurricanes',     'car'),
  ('NHL','carolina hurricanes',     'hurricanes'),
  ('NHL','carolina hurricanes',     'canes'),
  ('NHL','chicago blackhawks',      'chi blackhawks'),
  ('NHL','chicago blackhawks',      'chi'),
  ('NHL','chicago blackhawks',      'blackhawks'),
  ('NHL','colorado avalanche',      'col avalanche'),
  ('NHL','colorado avalanche',      'col'),
  ('NHL','colorado avalanche',      'avalanche'),
  ('NHL','colorado avalanche',      'avs'),
  ('NHL','columbus blue jackets',   'cbj blue jackets'),
  ('NHL','columbus blue jackets',   'cbj'),
  ('NHL','columbus blue jackets',   'blue jackets'),
  ('NHL','dallas stars',            'dal stars'),
  ('NHL','dallas stars',            'dal'),
  ('NHL','dallas stars',            'stars'),
  ('NHL','detroit red wings',       'det red wings'),
  ('NHL','detroit red wings',       'det'),
  ('NHL','detroit red wings',       'red wings'),
  ('NHL','edmonton oilers',         'edm oilers'),
  ('NHL','edmonton oilers',         'edm'),
  ('NHL','edmonton oilers',         'oilers'),
  ('NHL','florida panthers',        'fla panthers'),
  ('NHL','florida panthers',        'fla'),
  ('NHL','florida panthers',        'panthers'),
  ('NHL','los angeles kings',       'la kings'),
  ('NHL','los angeles kings',       'lak'),
  ('NHL','los angeles kings',       'kings'),
  ('NHL','minnesota wild',          'min wild'),
  ('NHL','minnesota wild',          'min'),
  ('NHL','minnesota wild',          'wild'),
  ('NHL','montreal canadiens',      'mtl canadiens'),
  ('NHL','montreal canadiens',      'mon canadiens'),
  ('NHL','montreal canadiens',      'mtl'),
  ('NHL','montreal canadiens',      'mon'),
  ('NHL','montreal canadiens',      'canadiens'),
  ('NHL','montreal canadiens',      'habs'),
  ('NHL','nashville predators',     'nsh predators'),
  ('NHL','nashville predators',     'nsh'),
  ('NHL','nashville predators',     'predators'),
  ('NHL','nashville predators',     'preds'),
  ('NHL','new jersey devils',       'nj devils'),
  ('NHL','new jersey devils',       'njd'),
  ('NHL','new jersey devils',       'devils'),
  ('NHL','new york islanders',      'nyi islanders'),
  ('NHL','new york islanders',      'ny islanders'),
  ('NHL','new york islanders',      'nyi'),
  ('NHL','new york islanders',      'islanders'),
  ('NHL','new york rangers',        'nyr rangers'),
  ('NHL','new york rangers',        'ny rangers'),
  ('NHL','new york rangers',        'nyr'),
  ('NHL','new york rangers',        'rangers'),
  ('NHL','ottawa senators',         'ott senators'),
  ('NHL','ottawa senators',         'ott'),
  ('NHL','ottawa senators',         'senators'),
  ('NHL','ottawa senators',         'sens'),
  ('NHL','philadelphia flyers',     'phi flyers'),
  ('NHL','philadelphia flyers',     'phi'),
  ('NHL','philadelphia flyers',     'flyers'),
  ('NHL','pittsburgh penguins',     'pit penguins'),
  ('NHL','pittsburgh penguins',     'pit'),
  ('NHL','pittsburgh penguins',     'penguins'),
  ('NHL','pittsburgh penguins',     'pens'),
  ('NHL','san jose sharks',         'sj sharks'),
  ('NHL','san jose sharks',         'sjs'),
  ('NHL','san jose sharks',         'sharks'),
  ('NHL','seattle kraken',          'sea kraken'),
  ('NHL','seattle kraken',          'sea'),
  ('NHL','seattle kraken',          'kraken'),
  ('NHL','st louis blues',          'stl blues'),
  ('NHL','st louis blues',          'stl'),
  ('NHL','st louis blues',          'blues'),
  ('NHL','st louis blues',          'st louis blues'),
  ('NHL','tampa bay lightning',     'tb lightning'),
  ('NHL','tampa bay lightning',     'tbl'),
  ('NHL','tampa bay lightning',     'tb'),
  ('NHL','tampa bay lightning',     'lightning'),
  ('NHL','tampa bay lightning',     'bolts'),
  ('NHL','toronto maple leafs',     'tor maple leafs'),
  ('NHL','toronto maple leafs',     'tor'),
  ('NHL','toronto maple leafs',     'maple leafs'),
  ('NHL','toronto maple leafs',     'leafs'),
  ('NHL','utah mammoth',            'uta mammoth'),
  ('NHL','utah mammoth',            'uta'),
  ('NHL','utah mammoth',            'mammoth'),
  ('NHL','utah mammoth',            'utah hockey club'),
  ('NHL','vancouver canucks',       'van canucks'),
  ('NHL','vancouver canucks',       'van'),
  ('NHL','vancouver canucks',       'canucks'),
  ('NHL','vegas golden knights',    'vgk golden knights'),
  ('NHL','vegas golden knights',    'veg golden knights'),
  ('NHL','vegas golden knights',    'vgk'),
  ('NHL','vegas golden knights',    'veg'),
  ('NHL','vegas golden knights',    'golden knights'),
  ('NHL','vegas golden knights',    'knights'),
  ('NHL','washington capitals',     'was capitals'),
  ('NHL','washington capitals',     'wsh capitals'),
  ('NHL','washington capitals',     'was'),
  ('NHL','washington capitals',     'wsh'),
  ('NHL','washington capitals',     'capitals'),
  ('NHL','washington capitals',     'caps'),
  ('NHL','winnipeg jets',           'wpg jets'),
  ('NHL','winnipeg jets',           'wpg'),
  ('NHL','winnipeg jets',           'jets')
on conflict (sport, alias) do nothing;

-- ============================================================================
-- NFL (32)
-- ============================================================================
insert into team_aliases (sport, canonical, alias) values
  ('NFL','arizona cardinals',       'ari cardinals'),
  ('NFL','arizona cardinals',       'ari'),
  ('NFL','arizona cardinals',       'az'),
  ('NFL','arizona cardinals',       'cardinals'),
  ('NFL','atlanta falcons',         'atl falcons'),
  ('NFL','atlanta falcons',         'atl'),
  ('NFL','atlanta falcons',         'falcons'),
  ('NFL','baltimore ravens',        'bal ravens'),
  ('NFL','baltimore ravens',        'bal'),
  ('NFL','baltimore ravens',        'ravens'),
  ('NFL','buffalo bills',           'buf bills'),
  ('NFL','buffalo bills',           'buf'),
  ('NFL','buffalo bills',           'bills'),
  ('NFL','carolina panthers',       'car panthers'),
  ('NFL','carolina panthers',       'car'),
  ('NFL','carolina panthers',       'panthers'),
  ('NFL','chicago bears',           'chi bears'),
  ('NFL','chicago bears',           'chi'),
  ('NFL','chicago bears',           'bears'),
  ('NFL','cincinnati bengals',      'cin bengals'),
  ('NFL','cincinnati bengals',      'cin'),
  ('NFL','cincinnati bengals',      'bengals'),
  ('NFL','cleveland browns',        'cle browns'),
  ('NFL','cleveland browns',        'cle'),
  ('NFL','cleveland browns',        'browns'),
  ('NFL','dallas cowboys',          'dal cowboys'),
  ('NFL','dallas cowboys',          'dal'),
  ('NFL','dallas cowboys',          'cowboys'),
  ('NFL','denver broncos',          'den broncos'),
  ('NFL','denver broncos',          'den'),
  ('NFL','denver broncos',          'broncos'),
  ('NFL','detroit lions',           'det lions'),
  ('NFL','detroit lions',           'det'),
  ('NFL','detroit lions',           'lions'),
  ('NFL','green bay packers',       'gb packers'),
  ('NFL','green bay packers',       'gbp'),
  ('NFL','green bay packers',       'gb'),
  ('NFL','green bay packers',       'packers'),
  ('NFL','houston texans',          'hou texans'),
  ('NFL','houston texans',          'hou'),
  ('NFL','houston texans',          'texans'),
  ('NFL','indianapolis colts',      'ind colts'),
  ('NFL','indianapolis colts',      'ind'),
  ('NFL','indianapolis colts',      'colts'),
  ('NFL','jacksonville jaguars',    'jax jaguars'),
  ('NFL','jacksonville jaguars',    'jac jaguars'),
  ('NFL','jacksonville jaguars',    'jax'),
  ('NFL','jacksonville jaguars',    'jac'),
  ('NFL','jacksonville jaguars',    'jaguars'),
  ('NFL','jacksonville jaguars',    'jags'),
  ('NFL','kansas city chiefs',      'kc chiefs'),
  ('NFL','kansas city chiefs',      'kc'),
  ('NFL','kansas city chiefs',      'chiefs'),
  ('NFL','las vegas raiders',       'lv raiders'),
  ('NFL','las vegas raiders',       'lvr'),
  ('NFL','las vegas raiders',       'lv'),
  ('NFL','las vegas raiders',       'raiders'),
  ('NFL','los angeles chargers',    'la chargers'),
  ('NFL','los angeles chargers',    'lac chargers'),
  ('NFL','los angeles chargers',    'lac'),
  ('NFL','los angeles chargers',    'chargers'),
  ('NFL','los angeles rams',        'la rams'),
  ('NFL','los angeles rams',        'lar rams'),
  ('NFL','los angeles rams',        'lar'),
  ('NFL','los angeles rams',        'rams'),
  ('NFL','miami dolphins',          'mia dolphins'),
  ('NFL','miami dolphins',          'mia'),
  ('NFL','miami dolphins',          'dolphins'),
  ('NFL','minnesota vikings',       'min vikings'),
  ('NFL','minnesota vikings',       'min'),
  ('NFL','minnesota vikings',       'vikings'),
  ('NFL','minnesota vikings',       'vikes'),
  ('NFL','new england patriots',    'ne patriots'),
  ('NFL','new england patriots',    'nwe'),
  ('NFL','new england patriots',    'ne'),
  ('NFL','new england patriots',    'patriots'),
  ('NFL','new england patriots',    'pats'),
  ('NFL','new orleans saints',      'no saints'),
  ('NFL','new orleans saints',      'nor'),
  ('NFL','new orleans saints',      'no'),
  ('NFL','new orleans saints',      'saints'),
  ('NFL','new york giants',         'ny giants'),
  ('NFL','new york giants',         'nyg'),
  ('NFL','new york giants',         'giants'),
  ('NFL','new york jets',           'ny jets'),
  ('NFL','new york jets',           'nyj'),
  ('NFL','new york jets',           'jets'),
  ('NFL','philadelphia eagles',     'phi eagles'),
  ('NFL','philadelphia eagles',     'phi'),
  ('NFL','philadelphia eagles',     'eagles'),
  ('NFL','pittsburgh steelers',     'pit steelers'),
  ('NFL','pittsburgh steelers',     'pit'),
  ('NFL','pittsburgh steelers',     'steelers'),
  ('NFL','san francisco 49ers',     'sf 49ers'),
  ('NFL','san francisco 49ers',     'sfo'),
  ('NFL','san francisco 49ers',     'sf'),
  ('NFL','san francisco 49ers',     '49ers'),
  ('NFL','san francisco 49ers',     'niners'),
  ('NFL','seattle seahawks',        'sea seahawks'),
  ('NFL','seattle seahawks',        'sea'),
  ('NFL','seattle seahawks',        'seahawks'),
  ('NFL','tampa bay buccaneers',    'tb buccaneers'),
  ('NFL','tampa bay buccaneers',    'tam'),
  ('NFL','tampa bay buccaneers',    'tb'),
  ('NFL','tampa bay buccaneers',    'buccaneers'),
  ('NFL','tampa bay buccaneers',    'bucs'),
  ('NFL','tennessee titans',        'ten titans'),
  ('NFL','tennessee titans',        'ten'),
  ('NFL','tennessee titans',        'titans'),
  ('NFL','washington commanders',   'was commanders'),
  ('NFL','washington commanders',   'wsh commanders'),
  ('NFL','washington commanders',   'was'),
  ('NFL','washington commanders',   'wsh'),
  ('NFL','washington commanders',   'commanders')
on conflict (sport, alias) do nothing;
